# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/.Xil/Vivado-26660-Caasi/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tfgg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/nanoProcesseur_package.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/ALU.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Address_Decode.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Data_Multiplexer.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Instruction_Register.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Operandes_Multiplexer.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Operandes_Register.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Output_Register.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Program_Counter.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/RAM.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/ROM.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Sequenceur.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/Status_Register.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/W_Register.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/nanoProcesseur.vhd}
      {C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/Vivado_nanoProcesseur.srcs/sources_1/imports/design.hdl/nanoControleur.vhd}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top nanoControleur
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Isaac/OneDrive/Bureau/Hearc/Di Applied/Vivado_nanoProcesseur/.Xil/Vivado-26660-Caasi/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
