--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 9.3 Revision 2 from HDL Works B.V.
--
-- Ease library  : Work
-- HDL library   : Work
-- Host name     : NB21-B0I-YME
-- User name     : yves.meyer
-- Time stamp    : Tue Jan  3 10:07:22 2023
--
-- Designed by   : M.Meyer/Y.Meyer
-- Company       : Haute Ecole Arc
-- Project info  : nanoProcesseur
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Package Work.nanoProcesseur_package
-- Last modified : Tue Jan  3 10:06:54 2023
--------------------------------------------------------------------------------

library ieee;
use ieee.numeric_std.all;
use ieee.std_logic_1164.all;
package variables is
 
 -- Variables 
  constant S                   : std_logic_vector(7 downto 0) := X"9F";
  constant usiMulA             : std_logic_vector(7 downto 0) := X"80";
  constant usiMulB             : std_logic_vector(7 downto 0) := X"81";
  constant usiTempMul          : std_logic_vector(7 downto 0) := X"82";
  constant usiMostResultMul    : std_logic_vector(7 downto 0) := X"83";
  constant usiLessResultMul    : std_logic_vector(7 downto 0) := X"84";
  constant usiCounter          : std_logic_vector(7 downto 0) := X"85";
  constant usiMemPorta         : std_logic_vector(7 downto 0) := X"86";
  constant usiMemPortb         : std_logic_vector(7 downto 0) := X"87";
  
  -- Var const
  constant None                : std_logic_vector(7 downto 0) := X"00";
  constant PortA               : std_logic_vector(7 downto 0) := X"20";
  constant PortB               : std_logic_vector(7 downto 0) := X"21";
  constant PortC               : std_logic_vector(7 downto 0) := X"21";
  
  -- Entry
  constant MAIN                : std_logic_vector(7 downto 0) := X"10";
  
end package variables ;
package body variables is

end package body variables ;
